### ISSUE TITLE
Where is the C++ code for the Chapters 2, 3, etc. 

### ISSUE THREAD

**Issue by pinnaclesystemsgroup** [Apress/Robot-Operating-System-Abs-Begs#2]
My copy of this book contains several C++ files that are not in this repo. What gives?

**Comment by qboticslabs** [comment]
@pinnaclesystemsgroup The C++ code in the chapter 2 is already in this repo. Also, chapter 3 is having python code.

**Comment by pinnaclesystemsgroup** [comment]
Hello

There seems to be a disconnect here between my post that the GitHub book
code repo and the software examples in the book do not match - there are
book code examples that are NOT in the book code repo.

If you would check the book yourself and make a simple list of the book
diagrams and then compare that list with the book repo code you will find
the repo has almost none of the code given in the book diagrams.

Whether the book code as shown in the diagrams is missing because the
author felt it didn't need to be placed into repo (redundant) or the book
code in the diagrams is grouped together into a single, the repo code is
NOT complete.

What I was expecting is the book code repo would have every piece of
executable code organized by chapter, and then page number so it would be
easy to follow along and compile then execute the book code,

P. Riley

**Comment by qboticslabs** [comment]
Hi @pinnaclesystemsgroup 

Sorry for the issue. If possible can you mention the specific page number of the book which is having the issues? Or you can send me a detailed e-mail to qboticslabs@gmail.com so that we can support you and helps to solve the issue.

Regards

**Comment by pinnaclesystemsgroup** [comment]
Hello --

You asked I provide an example of the "gaps" I found between the book code
files and folders now posted to the book's GitHub repo and the book's code
listing.

Please check the folder names "Chap 2" in the repo and compare its files
to:  "Listing 2-1. Example Code to Demonstrate C++ Class and Struct." on
book pages 69-74. You can verify the repo does not contain the "Robot
Classes or Strucs" shown in the book's listings on those pages.

**Comment by pinnaclesystemsgroup** [comment]
Hello --

I am posting this as a public apology for my recent post claiming the repo
was not complete and code was missing.

I just refreshed my copy of the repo with a fresh pull and ran git log on
the cloned repo and the code for Chap2 is present in the repo.

My sincere apologies.

**Comment by qboticslabs** [comment]
Hi, @pinnaclesystemsgroup It's totally fine. 

Good to know your issue has been solved.
